#creating cluster using eksctl, this is the configuration file for creating cluster using eksctl, once we run eksctl create cluster -f eks.yaml, it will create a cluster with the name expense in the region us-east-1 with 3 spot instances of different instance types, if spot instances are not available, it will use on-demand instances
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig 

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceTypes: ["t3.medium"] #making sure that we are using different instance types under spot instances, so that if one instance type is not available, it will use other instance types
    desiredCapacity: 2
    spot: false 
    #using spot instances to reduce cost, if spot instances are not available, it will use on-demand instances